version: "3.9"
services:
  backend:
    build: ../backend
    container_name: todo-backend
    ports:
      - "3001:3001"
    networks:
      - todo-net

  frontend:
    build: ../frontend
    container_name: todo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
